import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useCollection } from "react-firebase-hooks/firestore";
import { db } from '../firebase';
import firebase from "firebase/compat/app"
export default function Home() {
  const [snapShot, loading, error]= useCollection(db.collection("messages"),add({
    message:'',
    timestamp:firebase.firestore.FieldValue.serverTimeStamp()
  }))
  const onSubmit = () => {

  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Translator App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hi </h1>
      <form>
        <input type="text" />
        <button onClick={onSubmit} type="submit">
          Send{" "}
        </button>
      </form>
    </div>
  );
}
